version: '3'
services:
  postgres:
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=bakery
      - POSTGRES_USER=bakery
      - POSTGRES_PASSWORD=bakery
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
